os:
- linux
language: php
php:
- '7.1'
- '7.2'

cache:
  directories:
  - "$HOME/.composer/cache/files"

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-text
