language: php
php:
  - '5.6'
  - '7.1'

#before_install:
#  - cd src

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: POjzyOncqDNxgylryiknUtBVWDCnkJ4ZdeJqdbTpXov9EQAIPQKhQOx1rtBRX942Jzd/Ncp0D8mBW0QWlCFDNuQ6deWVGOCeZgE84nXLKRFSGMxz9eaIIdcCocEXIIA47GzAPdy4ZOXu7j7/VLXrDGZIxkAad7ndb6utmO2QZf+endkfvwPDiiKx5Lhrzwjr2dA2tFGP2RxbSom6Q4rha1oBdfuqwU9kpJwvUf59G/CrEmHsslFm63XS0CFASXzM9lU0LIXaPDt9BxlV+Xv4phyuBoVTEh7+t9oqjZRzQyZYyn5y8IHzqck3xsvSh+no6jedwxoCQZBZwGTKaWE+ea7gikGYq1XsFISEji+9M+r/MtfBEPBj315IurLI1YuEb3QC9A85YNgf8xHaXppJp+7pW5lrNs7wRWtLUhYcjnVOqanHpnuQAdEj46z0eSXpJ11cYo7Pr1VHUGwBozuwbzcHQhJyVJy/CwEex/xsUooaEoIJXlsPHzuAJLgEo/ILCvtS9t/BGdjZXMGLco2Ifznz6295gxalvm6jk0Z7Z4UEtnFUsT2VkJfZUlzygcVGlYFZIv3vXYtQAUG2RQJ8pFnkfDZGnenafLo4UPA+XcbpYTfuCtZCITwzlY2a7EqNxFSNUH08KnsErHKaBcuyoIizv4Vykr/nT+0nx6e+gPY=
  app:
    master: codethesaurus-prod
    staging: codethesaurus-staging
    develop: codethesaurus-develop
