blank_issues_enabled: false
contact_links:
  - name: Code Thesaurus Twitter
    url: https://twitter.com/codethesaurus
    about: The Twitter account for the project
  - name: Code Thesaurus Team Email
    url: mailto: coreteam@codethesaur.us
    about: The email address for the people on the core team of the project
