name: JSON Validator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v1.0.3
